##
##
##

gpus: 
  - 0

# possible names ntu60-xsub, ntu60-xview, ntu120-xsub, ntu120-xset
datasets:
  - name: 'ntu60-xsub'
    dataset_path: 'data/ntu60-xsub'
    generate_args: 
      ignored_file: 'data/ignore.txt'
      ntu60_path: 'data/nturgbd_skeletons_s001_to_s017'
    num_frames: 64

models:
  - name: 'MS-STA'
    pretrained: '' # mandatory field for tests

tests:
  - batch_size: 64

trainings: 
  - model: 0
    dataset: 0
    train_batch_size: 4
    eval_batch_size: 8
    optimizer: 0
    scheduler: 0
    gpus:
      - 0
    seed: 0
    max_epoch: 64
    resume: False

optimizers: 
  - name: 'Adam'
    lr: 0.1
    betas: 
      - 0.9
      - 0.99
    weight_decay: 0.0001
  - name: 'SGD'
    lr: 0.1
    momentum: 0.9
    nesterov: False
    weight_decay: 0.0001

lr_schedulers: 
  - name: 'LinearLR'
